version: "3.3"
services:
  postgres:
    image: postgres:10.2-alpine
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecex_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  mix:
  hex:

